version: "3.1"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
